name: CI

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['*']

concurrency:
  group: ${{ github.workflow }}__${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      # fix: https://github.com/nodejs/corepack/issues/612
      - name: Set alternate npm integrity keys
        run: |
          echo COREPACK_INTEGRITY_KEYS="$(curl https://registry.npmjs.org/-/npm/v1/keys | jq -c '{npm: .keys}')" >> $GITHUB_ENV

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Format
        run: pnpm format

      # - name: Build
      #   run: pnpm build
